### ISSUE TITLE
Widget directive contained block are removed

### ISSUE THREAD

**Issue by HirokazuNishi** [magesuite/content-constructor-admin#3]
# Environment

- Magento Open Source 2.3.4
- MageSuite 3.0.2
- magesuite-content-constructor-admin: v2.12.0
- PHP 7.2.x / 7.3.x
- Chrome 80.x with Mac OS 10.15.3

# Description

Contents data is set blank when CMS Block contains widget directive. Before v2.10.0, there was no content constructor feature on CMS block edit form. All editing features were worked fine as expected. After upgrading v2.12.0, cms block data contains widget directives is erased when block edit page is displayed.

# How to reproduce

1. Login to Magento admin
2. Access to Block list
3. Create new block
4. Insert widget into content area
5. Save block and reload page
6. Content area is blank.

# Expected result

- Content should not be erased if it contains widget directive.

# Actual result

- Content is blank. During page loading time, content data is shown. After loading completed, it's erased.

**Comment by diwipl** [comment]
We're aware, we will revert that feature in admin panel today. 
I will let you know when this happens.

**Comment by diwipl** [comment]
New version with CC in statick block disabled was released. We will release this functionality after we'll deal with all the issues.
